import os
from typing import Any

from omegaconf import OmegaConf

from cl.metrics import TaskMetricsTracker
from cl.shared import setup_logger
from cl.visualizations import create_gif
import wandb

logger = setup_logger(__name__)


class RunLogger:
    def __init__(self, config: OmegaConf, disable_wandb: bool = False):
        self.config = config
        self.wandb_project = config.project
        self.wandb_entity = config.get("entity", None)

        if disable_wandb:
            # For multi-seed training: don't create the main run
            # (K seed runs will be created separately)
            self.wandb_run = None
            # Generate a unique run name without W&B hash
            import uuid
            self.run_name = f"{config.name}_{config.agent.name}_{config.experiment_name}"
            self.run_id = str(uuid.uuid4())[:8]
        else:
            self.wandb_run = self._init_wandb_run(self.config)
            self.run_name = self.wandb_run.name
            self.run_id = self.wandb_run.id

        self.results_dir = os.path.join(self.config.results_path, self.run_id)
        self.log_interval_episodes = self.config.trainer.get("log_interval_episodes", 10)
        self.gif_interval_frames = self.config.trainer.get("gif_interval_frames", 1000000)
        self.log_gif_to_wandb = self.config.trainer.get("log_gif_to_wandb", False)
        self.last_log_episode = 0
        self.last_gif_frame = 0

        # Create main results directory
        os.makedirs(self.results_dir, exist_ok=True)

        # Create environment subdirectories
        for env_name in self.config.envs:
            os.makedirs(os.path.join(self.results_dir, env_name), exist_ok=True)

    @staticmethod
    def _init_wandb_run(config: OmegaConf) -> wandb.sdk.wandb_run.Run:
        """
        Initialize a new wandb run with the provided config.

        This function:
        1. Initializes a wandb run with the provided config
        2. Creates a custom run name using the config file name, model name, experiment name, and run ID
        3. Saves the original config as a YAML file in a wandb artifact

        The run name follows the format: {config.name}_{config.agent.name}_{config.experiment_name}_{wandb_run_id}

        Args:
            config (OmegaConf): The configuration to use for this run

        Returns:
            wandb.sdk.wandb_run.Run: The initialized wandb run object
        """
        wandb_run = wandb.init(
            entity=config.entity,
            project=config.project,
            config=OmegaConf.to_container(config, resolve=True),
            mode="offline" if config.offline else "online",
        )

        # Create the new run name and assign it to the wandb run
        wandb_run.name = "_".join([
            config.name,             # Created from both environment and model config file names
            config.agent.name,       # Model name from the model config
            config.experiment_name,  # Manually set in the model config
            wandb_run.id,            # Generated by wandb
        ])

        # Upload the config in the original YAML format
        artifact = wandb.Artifact(name="config", type="config")
        config_path = "config.yaml"
        with open(config_path, "w") as f:
            f.write(OmegaConf.to_yaml(config))
        artifact.add_file(config_path)
        wandb_run.log_artifact(artifact)

        try:
            os.remove(config_path)  # Remove the temporary file
        except OSError as e:
            logger.warning(f"Could not remove temporary config file {config_path}: {e}")

        return wandb_run

    def initialize(self) -> None:
        """
        Initialize the logger variables.
        Only used for training, as during evaluation we log aggregated metrics, and
        gifs are not logged.
        It should be called at the beginning of each training task.
        """
        self.last_log_episode = 0
        self.last_gif_frame = 0

    def register_metrics(
        self,
        metrics_tracker: TaskMetricsTracker,
        metric_sources: str | list[str],
    ) -> None:
        """
        Registers metrics for logging to the wandb run with the custom step metric.

        Args:
            metrics_tracker (TaskMetricsTracker): The metrics tracker containing the step metric and metric names.
            metric_sources (list[str]): List of metric sources (e.g., env names or 'aggregated' for aggregated metrics) to register metrics for.
        """
        step_metric = metrics_tracker.step_metric
        metric_names = metrics_tracker.get_metric_names()
        if isinstance(metric_sources, str):
            metric_sources = [metric_sources]

        logger.info(
            f"Registering metrics {metric_names!r} with step metric {step_metric!r} "
        )

        for source_name in metric_sources:
            for metric_name in metric_names:
                name = f"{metrics_tracker.mode}/{source_name}/{metric_name}"
                self.wandb_run.define_metric(name, step_metric=step_metric)

    def log_eval_data(
        self,
        metrics_tracker: TaskMetricsTracker,
        metrics: dict[str, Any],
        current_set: int,
    ) -> None:
        """
        Logs evaluation data to wandb.

        Args:
            metrics_tracker (TaskMetricsTracker): The metrics tracker containing the current metric prefix and step metric.
            metrics (dict[str, Any]): The evaluation metrics to log.
            current_set (int): The current evaluation set number.
        """
        step_metric = metrics_tracker.step_metric
        metric_prefix = metrics_tracker.current_metric_prefix
        # Log the metrics to wandb
        metrics = {f"{metric_prefix}/{k}": v for k, v in metrics.items()}
        metrics[step_metric] = current_set
        self.wandb_run.log(metrics)

    def log_episode_metrics(self, metrics_tracker: TaskMetricsTracker) -> None:
        """
        Logs episode metrics to wandb and console during training.

        Args:
            metrics_tracker (TaskMetricsTracker): The metrics tracker containing the environment metrics.
        """
        metrics_buffer = metrics_tracker.get_latest_metrics()
        metrics_aggregated = metrics_tracker.get_aggregated_logging_metrics()

        # Check if the buffer is empty
        if not metrics_buffer:
            return

        step_metric = metrics_tracker.step_metric
        metric_prefix = metrics_tracker.current_metric_prefix
        current_episode = metrics_tracker.env_total_episodes

        # Iterate over the finished episodes and log to wandb
        for episode_metrics in metrics_buffer:
            episode_metrics = {
                f"{metric_prefix}/{k}": v for k, v in episode_metrics.items()
            }
            episode_metrics[step_metric] = current_episode
            self.wandb_run.log(episode_metrics)

        # Log to console
        if current_episode >= self.last_log_episode + self.log_interval_episodes:
            self.last_log_episode = current_episode

            # Format values depending on their type
            episode_info = " | ".join(
                [
                    f"{k}: {v:.4f}" if isinstance(v, float) else f"{k}: {v}"
                    for k, v in metrics_aggregated.items()
                ]
            )
            logger.info(episode_info)

    def log_episode_gif(self, metrics_tracker: TaskMetricsTracker) -> None:
        """
        Logs a GIF of the latest episode to wandb and saves it to the results directory.

        Args:
            metrics_tracker (TaskMetricsTracker): The metrics tracker containing the current environment name and mode.
        """
        current_frame = metrics_tracker.env_total_frames

        # Skip if the GIF interval has not been reached
        if current_frame < self.last_gif_frame + self.gif_interval_frames:
            return

        self.last_gif_frame = current_frame

        current_metric_prefix = metrics_tracker.current_metric_prefix
        current_env_name = metrics_tracker.current_env_name
        current_results_dir = os.path.join(self.results_dir, current_env_name)
        current_episode = metrics_tracker.env_total_episodes

        logger.info(
            f"Saving GIF for {current_results_dir} episode {current_episode}..."
        )

        # Create the GIF, save it, and log to wandb
        gif_filepath = os.path.join(
            current_results_dir, f"episode_{current_episode}.gif"
        )

        # For now saving only from env0
        episode_recording = metrics_tracker.get_latest_episode_recording(env_idx=0)
        if episode_recording is None:
            logger.warning("No episode recording found to create a GIF.")
            return

        # Create and log the GIF
        try:
            create_gif(
                frames=episode_recording["image"],
                directions=episode_recording.get("direction", None),
                filename=gif_filepath,
            )
            if not self.log_gif_to_wandb:
                return
            # WandB filename without prefix to store in the media folder
            gif_wandb_name = f"{current_metric_prefix}/episode_{current_episode}"
            self.wandb_run.log(
                {gif_wandb_name: wandb.Video(gif_filepath, format="gif")}
            )
        except Exception as e:
            logger.error(f"Failed to create GIF {gif_filepath}: {e}")
